services:
  tg_vpn:
    build: .
    container_name: tg_vpn
    env_file:
      - .env
    networks:
      - vpn_bot_network
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: tg_vpn_postgres
    env_file:
      - .env
    ports:
      - "45432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vpn_bot_network

volumes:
  postgres_data:
    driver: local

networks:
  vpn_bot_network:
    driver: bridge
